In [11]:
import pandas as pd
import numpy as np

In [12]:
df=pd.read_csv("sample_data.csv")

In [13]:
# The students can perform:
#     • Rename columns 
df=df.rename(columns={"Emp ID":"Employee ID","Years Exp":"Years of Experience"}) 
df

,Employee ID,Employee Name,AGE,Skill Set,Years of Experience,Salary (INR),Date Of Joining,Department,Remarks
0,EMP001,Rahul Sharma,25,Python,2,450000,12-01-2023,IT,Good
1,EMP002,Anita Devi,28,Java,4,600000,2022/05/11,IT,NaN
2,EMP003,Kiran Kumar,31,python,5,720000,15-Jan-2021,IT,Excellent
3,EMP004,Priya Nair,29,Data Science,3,650000,2021-07-20,Analytics,NaN
4,EMP005,Arjun,27,C++,2,520000,10/10/2022,Development,Good
...,...,...,...,...,...,...,...,...,...
86,EMP086,Koushik,28,Machine Learning,4,720000,2021-12-12,AI,NaN
87,EMP087,Aarthi,24,Python,1,350000,2024-01-10,IT,NaN
88,EMP088,Pradeep,33,Data Science,8,1100000,2016-04-14,Analytics,NaN
89,EMP089,Rohini,29,SQL,4,650000,2021-08-20,Database,NaN
90,EMP090,Vijay,28,C++,3,580000,2022-09-09,Development,NaN

In [14]:
#  remove duplicates
df.drop_duplicates()
df

,Employee ID,Employee Name,AGE,Skill Set,Years of Experience,Salary (INR),Date Of Joining,Department,Remarks
0,EMP001,Rahul Sharma,25,Python,2,450000,12-01-2023,IT,Good
1,EMP002,Anita Devi,28,Java,4,600000,2022/05/11,IT,NaN
2,EMP003,Kiran Kumar,31,python,5,720000,15-Jan-2021,IT,Excellent
3,EMP004,Priya Nair,29,Data Science,3,650000,2021-07-20,Analytics,NaN
4,EMP005,Arjun,27,C++,2,520000,10/10/2022,Development,Good
...,...,...,...,...,...,...,...,...,...
86,EMP086,Koushik,28,Machine Learning,4,720000,2021-12-12,AI,NaN
87,EMP087,Aarthi,24,Python,1,350000,2024-01-10,IT,NaN
88,EMP088,Pradeep,33,Data Science,8,1100000,2016-04-14,Analytics,NaN
89,EMP089,Rohini,29,SQL,4,650000,2021-08-20,Database,NaN
90,EMP090,Vijay,28,C++,3,580000,2022-09-09,Development,NaN

In [15]:
#     • Handle null values (drop) 
df.dropna()

,Employee ID,Employee Name,AGE,Skill Set,Years of Experience,Salary (INR),Date Of Joining,Department,Remarks
0,EMP001,Rahul Sharma,25,Python,2,450000,12-01-2023,IT,Good
2,EMP003,Kiran Kumar,31,python,5,720000,15-Jan-2021,IT,Excellent
4,EMP005,Arjun,27,C++,2,520000,10/10/2022,Development,Good

In [16]:
# • Handle null values (fill)
df.fillna({"Employee ID": 000,"Employee Name": "abcd","AGE": 20,"Remarks": "good"}, inplace=True)
df

,Employee ID,Employee Name,AGE,Skill Set,Years of Experience,Salary (INR),Date Of Joining,Department,Remarks
0,EMP001,Rahul Sharma,25,Python,2,450000,12-01-2023,IT,Good
1,EMP002,Anita Devi,28,Java,4,600000,2022/05/11,IT,good
2,EMP003,Kiran Kumar,31,python,5,720000,15-Jan-2021,IT,Excellent
3,EMP004,Priya Nair,29,Data Science,3,650000,2021-07-20,Analytics,good
4,EMP005,Arjun,27,C++,2,520000,10/10/2022,Development,Good
...,...,...,...,...,...,...,...,...,...
86,EMP086,Koushik,28,Machine Learning,4,720000,2021-12-12,AI,good
87,EMP087,Aarthi,24,Python,1,350000,2024-01-10,IT,good
88,EMP088,Pradeep,33,Data Science,8,1100000,2016-04-14,Analytics,good
89,EMP089,Rohini,29,SQL,4,650000,2021-08-20,Database,good
90,EMP090,Vijay,28,C++,3,580000,2022-09-09,Development,good

In [17]:
#     • Change data types 
print(df.dtypes)

Employee ID            object
 Employee Name         object
AGE                    object
Skill Set              object
Years of Experience    object
Salary (INR)           object
Date Of Joining        object
Department             object
Remarks                object
dtype: object

In [19]:
print(df["AGE"].unique())

['25' '28' '31' '29' '27' 20 '35' '22' '45' '30' 'twenty six' '24' '26'
 '32' '150' '-5' '33' '34' '23']

In [21]:
print(df["AGE"].dtype)
print(df["AGE"].head(10))

object
0    25
1    28
2    31
3    29
4    27
5    20
6    35
7    22
8    45
9    30
Name: AGE, dtype: object

In [22]:
print(df["Years of Experience"].unique())

['2' '4' '5' '3' '10' '1' '18' '6' '7' '8' nan 'three' '0' '-2' '40' '9']

In [23]:
df["Years of Experience"] = df["Years of Experience"].replace("three", 3)
df["Years of Experience"] = pd.to_numeric(df["Years of Experience"],errors="coerce")
df["Years of Experience"] = df["Years of Experience"].fillna(df["Years of Experience"].median())
df["Years of Experience"] = df["Years of Experience"].astype(int)
df.head()

,Employee ID,Employee Name,AGE,Skill Set,Years of Experience,Salary (INR),Date Of Joining,Department,Remarks
0,EMP001,Rahul Sharma,25,Python,2,450000,12-01-2023,IT,Good
1,EMP002,Anita Devi,28,Java,4,600000,2022/05/11,IT,good
2,EMP003,Kiran Kumar,31,python,5,720000,15-Jan-2021,IT,Excellent
3,EMP004,Priya Nair,29,Data Science,3,650000,2021-07-20,Analytics,good
4,EMP005,Arjun,27,C++,2,520000,10/10/2022,Development,Good

In [24]:
print(df.dtypes)

Employee ID            object
 Employee Name         object
AGE                    object
Skill Set              object
Years of Experience     int64
Salary (INR)           object
Date Of Joining        object
Department             object
Remarks                object
dtype: object

In [30]:
df.rename(columns={"AGE": "Age"}, inplace=True)

In [31]:
df.columns

Index(['Employee ID', ' Employee Name ', 'Age', 'Skill Set',
       'Years of Experience', 'Salary (INR)', 'Date Of Joining', 'Department',
       'Remarks'],
      dtype='object')

In [32]:
#     • Standardize names 

df.columns = df.columns.str.strip()
df["Employee Name"] = df["Employee Name"].str.title()
df["Employee Name"].head()

0     Rahul Sharma
1       Anita Devi
2     Kiran Kumar
3       Priya Nair
4            Arjun
Name: Employee Name, dtype: object

In [33]:
#     • Standardize skills 

df["Skill Set"] = df["Skill Set"].astype(str).str.title()
df["Skill Set"].head()

0          Python
1            Java
2          Python
3    Data Science
4             C++
Name: Skill Set, dtype: object

In [34]:
#     • Clean salary values 
print(df["Salary (INR)"].unique())

['450000' '600000' '720000' '650000' '520000' '780000' '950000' '300000'
 '1200000' '850000' '550000' '480000' '490000' '700000' '900000' '800000'
 '250000' '620000' '590000' '680000' '1000000' '610000' '750000' nan
 '5,50,000' '350000' '980000' '760000' '500000' '320000' '1100000'
 '280000' '650000 INR' '$500000' '4.8L' '920000' '510000' '690000'
 '580000' '640000' '380000' 'Nine Lakhs' '460000' '310000' '99999999']

In [35]:
df["Salary (INR)"] = df["Salary (INR)"].replace({"5,50,000": "550000","650000 INR": "650000","$500000": "500000",
    "4.8L": "480000","Nine Lakhs": "900000","99999999": "990000",0: "500000"})
print(df)

   Employee ID  Employee Name Age         Skill Set  Years of Experience  \
0       EMP001   Rahul Sharma  25            Python                    2
1       EMP002     Anita Devi  28              Java                    4
2       EMP003   Kiran Kumar   31            Python                    5
3       EMP004     Priya Nair  29      Data Science                    3
4       EMP005          Arjun  27               C++                    2
..         ...            ...  ..               ...                  ...
86      EMP086        Koushik  28  Machine Learning                    4
87      EMP087         Aarthi  24            Python                    1
88      EMP088        Pradeep  33      Data Science                    8
89      EMP089         Rohini  29               Sql                    4
90      EMP090          Vijay  28               C++                    3

   Salary (INR) Date Of Joining   Department    Remarks
0        450000      12-01-2023           IT       Good
1        600000      2022/05/11           IT       good
2        720000     15-Jan-2021           IT  Excellent
3        650000      2021-07-20    Analytics       good
4        520000      10/10/2022  Development       Good
..          ...             ...          ...        ...
86       720000      2021-12-12           AI       good
87       350000      2024-01-10           IT       good
88      1100000      2016-04-14    Analytics       good
89       650000      2021-08-20     Database       good
90       580000      2022-09-09  Development       good

[91 rows x 9 columns]

In [36]:
#     • Parse dates 
print(df["Date Of Joining"].dtype)

object

In [44]:
#Detect and remove outlier:
import pandas as pd

data = {
    'Salary': [30000, 35000, 40000, 45000, 50000, 1000000]
}

df = pd.DataFrame(data)

Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = df[(df['Salary'] < lower_limit) | (df['Salary'] > upper_limit)]

print("Outliers:")
print(outliers)

df = df[(df['Salary'] >= lower_limit) & (df['Salary'] <= upper_limit)]

print("Data after removing outliers:")
print(df)

Outliers:
    Salary
5  1000000
Data after removing outliers:
   Salary
0   30000
1   35000
2   40000
3   45000
4   50000

In [46]:
#validata ages and experience:
import pandas as pd

data = {
    'Age': [25, 30, -5, 150, 40],
    'Experience': [2, 5, 10, 200, -1]
}

df = pd.DataFrame(data)

df = df[
    (df['Age'] >= 18) & 
    (df['Age'] <= 100) &
    (df['Experience'] >= 0) &
    (df['Experience'] <= 50)
]

print(df)

   Age  Experience
0   25           2
1   30           5

In [47]:

import pandas as pd
from sklearn.preprocessing import LabelEncoder

data = {
    'Gender': ['Male', 'Female', 'Female', 'Male']
}

df = pd.DataFrame(data)

encoder = LabelEncoder()
df['Gender_Encoded'] = encoder.fit_transform(df['Gender'])

print(df)

   Gender  Gender_Encoded
0    Male               1
1  Female               0
2  Female               0
3    Male               1

In [48]:

import pandas as pd

data = {
    'City': ['Chennai', 'Mumbai', 'Delhi', 'Chennai']
}

df = pd.DataFrame(data)

df = pd.get_dummies(df, columns=['City'])

print(df)

   City_Chennai  City_Delhi  City_Mumbai
0          True       False        False
1         False       False         True
2         False        True        False
3          True       False        False

In [49]:
#Scale numerical columns:
import pandas as pd
from sklearn.preprocessing import StandardScaler

data = {
    'Age': [20, 30, 40, 50],
    'Salary': [20000, 40000, 60000, 80000]
}

df = pd.DataFrame(data)

numerical_columns = ['Age', 'Salary']

scaler = StandardScaler()

df[numerical_columns] = scaler.fit_transform(df[numerical_columns])

print(df)

        Age    Salary
0 -1.341641 -1.341641
1 -0.447214 -0.447214
2  0.447214  0.447214
3  1.341641  1.341641

In [50]:
#feature selection:
print(df.head())

        Age    Salary
0 -1.341641 -1.341641
1 -0.447214 -0.447214
2  0.447214  0.447214
3  1.341641  1.341641